/* Database schema to keep the structure of entire database. */

CREATE TABLE public.animals
(
    id integer NOT NULL,
    name text NOT NULL,
    date_of_birth date,
    escape_attempts integer,
    neutered boolean,
    weight_kg numeric,
    PRIMARY KEY (id)
)

-- ################################# DAY 2 ######################################

ALTER TABLE animals
ADD species VARCHAR;

-- ################################# DAY 3 ######################################

CREATE TABLE owners (
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	full_name varchar,
	age integer
);

CREATE TABLE species (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,	
  name varchar, 
  PRIMARY KEY (id)
);

ALTER TABLE animals
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE animals
DROP COLUMN species;

ALTER TABLE animals
ADD species_id integer;

ALTER TABLE animals
ADD FOREIGN KEY (species_id) REFERENCES species (id) ON DELETE CASCADE;

ALTER TABLE animals
ADD owner_id integer;

ALTER TABLE owners
ADD PRIMARY KEY (id);

ALTER TABLE animals
ADD FOREIGN KEY (owner_id) REFERENCES owners (id) ON DELETE CASCADE;